---
# Defines IPTABLES rules for bastionhosts
bastion_iptables_definitions:
  - chain: POSTROUTING
    jump: MASQUERADE
    out_interface: "{{ kube_master_wired_interface }}"
    source: "{{ dhcp_scope_subnet_id }}/{{ dhcp_scope_cidr }}"
    state: present
    table: nat
  - chain: FORWARD
    ctstate: RELATED,ESTABLISHED
    in_interface: "{{ kube_master_wired_interface }}"
    jump: ACCEPT
    out_interface: "{{ kube_master_vlan_interface }}"
    state: present
    table: filter
  - chain: FORWARD
    in_interface: "{{ kube_master_vlan_interface }}"
    jump: ACCEPT
    out_interface: "{{ kube_master_wired_interface }}"
    state: present
    table: filter
