---
kube_primary_domain: kube.black-pearl.com

kube_master: "{{ groups['kube_master'][0] }}" # determine through inventory (single master setup)
kube_users:
  - user: "{{ ansible_user }}"  # determine through inventory

# interface for external communication
kube_wired_interface: eth0

# ip for external communication
kube_external_ip: "{{ ansible_host }}"
