---
# static target IP endings per host
# these endings need to be aligned with the inventory file (hosts.ini)
# important for bootstrapping the network configuration
kube_slave_ip_ending:
  kube-r64-001: 201
  kube-r64-002: 202
  kube-r64-003: 203
  kube-r64-004: 204
  kube-r64-005: 205
  kube-r64-006: 206
  kube-r64-007: 207
kube_slave_subnet: 192.168.1

ansible_host: "{{ kube_slave_external_ip }}"

# interface for external communication (bastion interface)
kube_slave_wired_interface: eth0
# ip for external communication (bastion interface)
kube_slave_external_ip: "{{ kube_slave_subnet }}.{{ kube_slave_ip_ending[inventory_hostname] | default(None) or hostvars[inventory_hostname]['ansible_' + kube_slave_wired_interface ]['ipv4']['address'].split('.')[3] }}"

kube_slave_interface_profiles:
  - type: iface
    auto: lo
    interface: lo
    address_family: inet      # or inet6 or ipx
    address_method: loopback  # or dhcp
  - type: iface
    auto: "{{ kube_slave_wired_interface }}"
    allow_hotplug: "{{ kube_slave_wired_interface }}"
    interface: "{{ kube_slave_wired_interface }}"
    address_family: inet    # or inet6 or ipx
    address_method: static  # or dhcp
    cidr_notation: "{{ kube_slave_external_ip }}/24"
    address: "{{ kube_slave_external_ip }}"
    netmask: 255.255.255.0  # CIDR /24
    gateway: 192.168.1.1
    dns_nameservers:        # are there any local DNS Name Servers?
      - 192.168.1.103
      - 192.168.1.104
      - 192.168.1.1
