---
- name: Uninstalling DNSMasq
  apt:
    name: dnsmasq
    state: absent
    purge: true
  become: true
  when: dhcp_server != "dnsmasq"

- name: Uninstalling ISC-DHCP
  apt:
    name: isc-dhcp-server
    state: absent
    purge: true
  become: true
  when: dhcp_server != "isc-dhcp"

- name: Install and configure DNSMasq
  include_role:
    name: mrlesmithjr/ansible-dnsmasq
  vars:
  when: >
    ansible_os_family == "Debian"
    and dhcp_server == "dnsmasq"

- name: Start service
  include_tasks: 
    file: service/dnsmasq.yml
  vars:
  when: >
    ansible_os_family == "Debian"
    and dhcp_server == "dnsmasq"

- name: Install and configure ISC-DHCP
  include_role:
    name: mrlesmithjr/ansible-isc-dhcp
  vars:
  when: >
    ansible_os_family == "Debian"
    and dhcp_server == "isc-dhcp"

- name: Start service
  include_tasks: 
    file: service/isc-dhcp.yml
  vars:
  when: >
    ansible_os_family == "Debian"
    and dhcp_server == "isc-dhcp"
