---
- name: apt-get install vlan
  apt:
    # https://packages.debian.org/sid/vlan
    name: [ 'vlan' ]
    state: present
    force: yes
  when: _networking_use_vlan

- name: Setup Raspbian (dhcpcd.conf)
  include_tasks:
    file: static-ip/raspbian.yml
  when: _os_is_raspbian

# - name: Set Static IP for Ubuntu based Systems (> bionic; Netplan)
  ## deploy a netplan file
  # template:
  #   src: interfaces.j2
  #   dest: /etc/network/interfaces
  #   mode: 0644
  #   backup: true
  # become: true
  # register: _static_ip
  # when: >
  #     not _os_is_raspbian
  #     and (ansible_distribution == 'Ubuntu' and ansible_release == 'bionic')

- name: Setup Debian NetworkManager
  include_tasks: 
    file: static-ip/debian.yml
  when: >
      not _os_is_raspbian
      and not (ansible_distribution == 'Ubuntu' and ansible_release == 'bionic')
