---
- name: Detect network interfaces
  command: ip a show
  register: _interfaces

# - debug:
#     var: _interfaces

- name: Remove Flannel devices
  command: ip link delete flannel.1
  become: true
  when: >
        'flannel.1' in _interfaces['stdout']
