---
- name: Check if kubernetes is installed
  shell: kubeadm version
  register: _kubeadm_version
  ignore_errors: true # errors can be ignored here, as we use this variable just to uninstall
  changed_when: false
  failed_when: false

- name: Kubernetes Version Check
  debug:
    msg: "{{ ('Version:' + _kubeadm_version['stdout']) if _kubeadm_version['stdout'] else _kubeadm_version['stderr'] }}"
  changed_when: false

- name: If kubeadm exists, reset it
  command: kubeadm reset -f # remove '-f' for lower K8s Versions (< v1.11.0)
  become: true
  when: "'kubeadm version' in _kubeadm_version['stdout']"

- name: Uninstall all kubernetes-relevant packages
  apt:
    name: "{{ k8s_debian_packages }}"
    autoremove: true
    force: true
    state: absent
  ignore_errors: true

- name: Remove admin.conf file (as it is checked by kubernetes role)
  file:
    path: /etc/kubernetes/admin.conf
    state: absent
  become: true

- name: Remove Apt-Sources List
  file:
    path: /etc/apt/sources.list.d/apt_kubernetes_io.list
    state: absent
  become: true

- name: Remove Kubernetes and etcd artifacts
  file:
    path: "{{ item }}"
    state: absent
  become: true
  with_items:
    - /etc/kubernetes/*
    - /var/lib/kubelet/*
    - /var/lib/etcd/member
