---
- name: Remove Kubernetes Artifacts
  include_tasks: 
    file: "{{ item }}"
  with_items:
    - kubernetes-artifacts.yml

- name: Remove Flannel Artifacts
  include_tasks: 
    file: "{{ item }}"
  with_items:
    - flannel-artifacts.yml
