---
- name: Remove Kubernetes Artifacts
  include_tasks: 
    file: kubernetes-artifacts.yml

- name: Remove Flannel Artifacts
  include_tasks: 
    file: flannel-artifacts.yml

- name: Update apt cache
  apt:
    update_cache: yes
  become: true
      